### ISSUE TITLE
Super Saiyan Blue/Rose Visual Glitch 

### ISSUE THREAD

**Issue by Beandip69** [NuovaPrime/DBT-Issues#14] opened 2020-10-19 05:46 UTC
**Describe the bug**
When untransformed, a few lines of blue texture errors surround the player

**To Reproduce**
After recently switching traits with the Dragon Balls and transforming into Super Saiyan Blue / Rose, the bug occurs when untransforming. 

**Screenshots**
https://cdn.discordapp.com/attachments/721229903860596758/767622538205069332/unknown.png

**Other Mods**
HERO's Mod, Webmilio's Commons

**Additional Info**
N/A

**Comment by Tyndareus** [comment] 2020-10-19 14:18
Must be more to this issue, couldn't reproduce as suggested

**Comment by ChristmasGuyyy** [comment] 2020-10-19 14:31
@Tyndareus i reproduced it with transforming from god to blue or rose.

**Comment by Tyndareus** [comment] 2020-10-19 16:08
![cLQodKvt1v](https://user-images.githubusercontent.com/13440433/96476739-83438280-122d-11eb-880c-a68db5f0403c.gif)
![Zutafe03oK](https://user-images.githubusercontent.com/13440433/96476747-850d4600-122d-11eb-821f-a92daf32bbe0.gif)

First ones transforming normally, second one is transforming into god then using the transformation setter. Untransformed as normal

**Comment by NuovaPrime** [comment] 2021-01-26 01:25
Should be fixed.

**Closed as completed by NuovaPrime** 2021-01-26 01:25 UTC
Labels: Bug
