### ISSUE TITLE
Character Rotating Wrong While in flight

### ISSUE THREAD

**Issue by ChristmasGuyyy** [NuovaPrime/DBT-Issues#22] opened 2020-10-19 21:03 UTC
**Describe the bug**
while in flight, aura doesnt rotate, but the way the character rotates is just wrong

**To Reproduce**
No Clue

**Screenshots**
![Desktop-20201019-16172208](https://user-images.githubusercontent.com/73090750/96516945-a2daab00-122d-11eb-827b-0e24836b7d22.gif)

**Other Mods**
Heroes Mod

**Additional Info**

**Comment by ChristmasGuyyy** [comment] 2020-10-19 22:02
turns out this bug goes way further than i thought, 
https://discordapp.com/channels/280737768735506432/721229903860596758/767856859490942986

**Comment by ChristmasGuyyy** [comment] 2020-10-19 22:09
updated bug description and title

**Comment by AetherBreaker** [comment] 2020-10-26 12:57
I believe this is caused by using big bang attack while flying, since its supposed to angle you to face towards your cursor, except it doesnt stop doing that once you stop using it

**Comment by ChristmasGuyyy** [comment] 2020-10-27 02:53
@AetherBreaker yeah thinking back on it that is what i used before i triggered the bug

**Comment by zszeta** [comment] 2020-10-27 02:56
I can try to reproduce it right now

**Comment by NuovaPrime** [comment] 2021-01-26 01:28
Should be fixed.

**Closed as completed by NuovaPrime** 2021-01-26 01:28 UTC
Labels: Bug
